import json
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any

@dataclass
class CompileResult:
    success: bool
    output: dict[str, Any]
    error: str | None = None
    retryable: bool = False

class WorkflowCompiler:
    id = "workflow-compiler"

    def __init__(self, root: str | Path | None = None):
        self.root = Path(root) if root else Path(__file__).resolve().parents[2]

    def supports(self, capability: str) -> bool:
        return capability == "workflow-compile"

    @staticmethod
    def _node_id() -> str:
        return str(uuid.uuid4())

    def _compile_project(self, project: dict) -> dict:
        project_path = Path(project.get("project_path", ""))
        if not project_path.is_absolute():
            project_path = self.root / project_path

        manifest_path = project_path / "manifest.json"
        workflow_path = project_path / "workflow.json"

        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        abstract = json.loads(workflow_path.read_text(encoding="utf-8"))

        nodes = []
        connections = {}

        trigger_id = self._node_id()
        trigger_name = "OTH Trigger"
        nodes.append({
            "parameters": {},
            "id": trigger_id,
            "name": trigger_name,
            "type": "n8n-nodes-base.manualTrigger",
            "typeVersion": 1,
            "position": [0, 0],
        })
        previous = trigger_name

        for index, step in enumerate(abstract.get("steps", []), start=1):
            name = f"OTH Step {index}"
            node_id = self._node_id()
            nodes.append({
                "parameters": {
                    "jsCode": (
                        "return [{ json: { "
                        f"step: {json.dumps(step)}, "
                        "status: 'placeholder', "
                        "note: 'Replace this compiler placeholder with the "
                        "domain-specific node or agent action.' "
                        "} }];"
                    )
                },
                "id": node_id,
                "name": name,
                "type": "n8n-nodes-base.code",
                "typeVersion": 2,
                "position": [index * 260, 0],
            })
            connections.setdefault(previous, {"main": [[]]})
            connections[previous]["main"][0].append({
                "node": name,
                "type": "main",
                "index": 0,
            })
            previous = name

        compiled = {
            "name": manifest.get("title", "OTH Automation"),
            "nodes": nodes,
            "pinData": {},
            "connections": connections,
            "active": False,
            "settings": {},
            "versionId": str(uuid.uuid4()),
            "meta": {"othGenerated": True},
            "tags": [],
        }

        target = project_path / "n8n.workflow.json"
        target.write_text(json.dumps(compiled, indent=2), encoding="utf-8")

        flow_id = self._node_id()
        red_nodes = []
        red_nodes.append({
            "id": flow_id,
            "type": "tab",
            "label": compiled["name"],
            "disabled": False,
            "info": "Generated by OTH; provider fallback: Node-RED",
            "env": [],
        })
        inject_id = self._node_id()
        first_step_id = self._node_id() if abstract.get("steps") else None
        red_nodes.append({
            "id": inject_id,
            "type": "inject",
            "z": flow_id,
            "name": "OTH Trigger",
            "props": [{"p": "payload"}],
            "repeat": "",
            "crontab": "",
            "once": False,
            "onceDelay": 0.1,
            "topic": "",
            "payload": "",
            "payloadType": "date",
            "x": 120,
            "y": 120,
            "wires": [[first_step_id] if first_step_id else []],
        })
        step_ids = []
        for index, step in enumerate(abstract.get("steps", []), start=1):
            step_id = first_step_id if index == 1 else self._node_id()
            step_ids.append(step_id)
        for index, step in enumerate(abstract.get("steps", []), start=1):
            step_id = step_ids[index - 1]
            next_id = step_ids[index] if index < len(step_ids) else self._node_id()
            body = json.dumps({"step": step, "status": "placeholder"})
            red_nodes.append({
                "id": step_id,
                "type": "function",
                "z": flow_id,
                "name": f"OTH Step {index}",
                "func": "msg.oth = msg.oth || {}; msg.oth.steps = msg.oth.steps || []; "
                        + f"msg.oth.steps.push({body}); return msg;",
                "outputs": 1,
                "timeout": 0,
                "noerr": 0,
                "initialize": "",
                "finalize": "",
                "libs": [],
                "x": 360 + (index - 1) * 240,
                "y": 120,
                "wires": [[next_id]],
            })
        debug_id = step_ids[-1] if step_ids else inject_id
        result_id = self._node_id()
        red_nodes.append({
            "id": result_id,
            "type": "debug",
            "z": flow_id,
            "name": "OTH Result",
            "active": True,
            "tosidebar": True,
            "console": False,
            "tostatus": False,
            "complete": "oth",
            "targetType": "msg",
            "statusVal": "",
            "statusType": "auto",
            "x": 620 + max(0, len(step_ids) - 1) * 240,
            "y": 200,
            "wires": [],
        })
        if step_ids:
            red_nodes[-2]["wires"] = [[result_id]]
        red_target = project_path / "node-red.flow.json"
        red_target.write_text(json.dumps(red_nodes, indent=2), encoding="utf-8")

        return {
            "project_path": str(project_path),
            "workflow_path": str(target),
            "workflow_name": compiled["name"],
            "nodes": len(nodes),
            "node_red_workflow_path": str(red_target),
            "node_red_nodes": len(red_nodes),
            "active": False,
            "opportunity": project.get("opportunity", {}),
        }

    def execute(self, action: str, payload: dict) -> CompileResult:
        if action != "compile":
            return CompileResult(False, {}, f"Unsupported workflow-compile action: {action}")
        projects = payload.get("input", {}).get("projects", [])
        if not isinstance(projects, list):
            return CompileResult(False, {}, "input.projects must be a list")

        compiled = [self._compile_project(project) for project in projects[:10]]
        return CompileResult(True, {
            "compiled": compiled,
            "count": len(compiled),
            "next": [{"capability": "qa-validation", "action": "validate", "priority": 50}],
        })
